#!/usr/bin/env python3
"""
Group-level connectivity pipeline.

This script consumes subject-specific ROI time series generated by the
single-subject pipeline and computes group connectivity matrices (e.g.,
the tangent space embedding). Use this entry point after every subject
has finished preprocessing so that group-only analyses are isolated from
the individual runs.
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Tuple, Dict

import numpy as np
from nilearn.connectome import ConnectivityMeasure

# Make helper utilities available
SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR.parent / 'scripts'))

from utils.helpers import load_config, setup_logging, save_metadata  # noqa: E402


class GroupConnectivityPipeline:
    """Group-level FC computation based on saved ROI time series."""

    ALLOWED_METHODS = (
        'correlation',
        'partial correlation',
        'tangent',
        'covariance',
        'precision',
    )

    def __init__(self, config_path: str = None, methods: List[str] = None):
        self.config_path = config_path
        self.config = load_config(config_path)
        if methods is None:
            # Default to tangent since it is the one subject runs cannot handle
            methods = ['tangent']

        self.methods = methods
        self.logger = None

    @staticmethod
    def _normalize_method(method: str) -> str:
        normalized = method.replace('_', ' ').strip().lower()
        return normalized

    def _load_time_series(self, subjects: List[str], conn_dir: Path) -> Tuple[List[str], List[str], List[np.ndarray]]:
        """Load ROI time series for requested subjects."""
        available, missing, arrays = [], [], []

        for subject_id in subjects:
            ts_file = conn_dir / subject_id / f'{subject_id}_roi_timeseries.npy'
            if not ts_file.exists():
                missing.append(subject_id)
                continue

            data = np.load(ts_file)
            arrays.append(data)
            available.append(subject_id)

        if not arrays:
            raise ValueError("No ROI time series found for the requested subjects.")

        # Ensure all ROI counts match
        roi_counts = {arr.shape[1] for arr in arrays}
        if len(roi_counts) > 1:
            raise ValueError(f"ROI count mismatch across subjects: {roi_counts}")

        return available, missing, arrays

    def _compute_group_connectivity(self, time_series: List[np.ndarray], method: str) -> Tuple[str, np.ndarray, List[np.ndarray], np.ndarray]:
        """Compute group connectivity matrices for a specific method."""
        normalized = self._normalize_method(method)
        if normalized not in self.ALLOWED_METHODS:
            raise ValueError(f"Unsupported method '{method}'. Allowed: {self.ALLOWED_METHODS}")

        if normalized == 'tangent' and len(time_series) < 2:
            raise ValueError("Tangent space parametrization requires at least two subjects.")

        conn_measure = ConnectivityMeasure(kind=normalized)
        matrices = conn_measure.fit_transform(time_series)
        group_mean = np.mean(matrices, axis=0)
        reference = getattr(conn_measure, 'mean_', None)

        return normalized, group_mean, matrices, reference

    def run(self, subjects: List[str], conn_dir: str, output_dir: str) -> Dict:
        """Execute the group-level analysis."""
        conn_dir = Path(conn_dir)
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        log_dir = output_dir / 'logs'
        self.logger = setup_logging(
            str(log_dir),
            level=self.config['logging']['level']
        )

        self.logger.info("=" * 80)
        self.logger.info("GROUP CONNECTIVITY PIPELINE")
        self.logger.info("=" * 80)
        self.logger.info(f"Requested subjects: {subjects}")
        self.logger.info(f"Connectivity dir: {conn_dir}")
        self.logger.info(f"Output dir: {output_dir}")
        self.logger.info(f"Methods: {self.methods}")

        start_time = datetime.now()

        available, missing, time_series = self._load_time_series(subjects, conn_dir)
        self.logger.info(f"Included subjects: {available}")
        if missing:
            self.logger.warning(f"Missing subjects (no ROI time series): {missing}")

        if not available:
            raise ValueError("None of the requested subjects had ROI time series available.")

        method_results = {}
        for method in self.methods:
            normalized, group_matrix, subject_mats, reference = self._compute_group_connectivity(time_series, method)
            safe_name = normalized.replace(' ', '_')
            method_dir = output_dir / safe_name
            method_dir.mkdir(parents=True, exist_ok=True)

            group_file = method_dir / f'group_{safe_name}_mean.npy'
            np.save(group_file, group_matrix)
            self.logger.info(f"[{method}] Saved group mean matrix → {group_file}")

            reference_file = None
            if reference is not None:
                reference_file = method_dir / f'group_{safe_name}_reference.npy'
                np.save(reference_file, reference)
                self.logger.info(f"[{method}] Saved reference covariance → {reference_file}")

            subject_files = {}
            for subject_id, matrix in zip(available, subject_mats):
                sub_file = method_dir / f'{subject_id}_{safe_name}.npy'
                np.save(sub_file, matrix)
                subject_files[subject_id] = str(sub_file)

            method_results[normalized] = {
                'group_matrix': str(group_file),
                'reference': str(reference_file) if reference_file else None,
                'subject_matrices': subject_files,
                'n_subjects': len(available)
            }

        end_time = datetime.now()
        duration = (end_time - start_time).total_seconds()

        summary = {
            'start_time': str(start_time),
            'end_time': str(end_time),
            'duration_seconds': duration,
            'included_subjects': available,
            'missing_subjects': missing,
            'methods': list(method_results.keys()),
            'results': method_results,
            'status': 'completed'
        }

        summary_file = output_dir / 'group_connectivity_summary.json'
        save_metadata(summary, str(summary_file))
        self.logger.info(f"Summary saved to {summary_file}")

        return summary


def _load_subjects_from_file(path: str) -> List[str]:
    """Read subject IDs from a newline-delimited text file."""
    lines = Path(path).read_text().splitlines()
    return [line.strip() for line in lines if line.strip()]


def _discover_subjects(conn_dir: str) -> List[str]:
    """Find all subject directories in the connectivity output folder."""
    base = Path(conn_dir)
    return sorted([p.name for p in base.iterdir() if p.is_dir()])


def parse_args() -> argparse.Namespace:
    """Parse CLI flags."""
    parser = argparse.ArgumentParser(
        description="Compute group-level connectivity metrics from saved ROI time series."
    )
    parser.add_argument('--subjects', nargs='+', help="Explicit list of subject IDs to include")
    parser.add_argument('--subjects-file', help="Path to a text file with subject IDs (one per line)")
    parser.add_argument('--conn-dir', default=str(SCRIPT_DIR.parent / 'results' / 'connectivity'),
                        help="Directory containing subject ROI time series (default: fpreproc/results/connectivity)")
    parser.add_argument('--output-dir', default=str(SCRIPT_DIR.parent / 'results' / 'group_connectivity'),
                        help="Directory for group analysis outputs")
    parser.add_argument('--config', help="Optional config file (defaults to config/pipeline_config.yaml)")
    parser.add_argument('--methods', nargs='+',
                        help="Connectivity methods to compute (default: tangent)")
    return parser.parse_args()


def main() -> int:
    """Entry point for CLI execution."""
    args = parse_args()
    if args.subjects and args.subjects_file:
        print("Provide either --subjects or --subjects-file, not both.", file=sys.stderr)
        return 1

    if args.subjects_file:
        subjects = _load_subjects_from_file(args.subjects_file)
    elif args.subjects:
        subjects = args.subjects
    else:
        subjects = _discover_subjects(args.conn_dir)

    if not subjects:
        print("No subjects found. Please specify --subjects or confirm the connectivity directory.", file=sys.stderr)
        return 1

    pipeline = GroupConnectivityPipeline(args.config, methods=args.methods)

    try:
        pipeline.run(subjects, args.conn_dir, args.output_dir)
        print("\n" + "=" * 80)
        print("✓ GROUP CONNECTIVITY COMPLETED")
        print("=" * 80)
        print(f"Subjects: {len(subjects)}")
        print(f"Methods: {pipeline.methods}")
        print(f"Results directory: {args.output_dir}")
        print("=" * 80)
        return 0
    except Exception as exc:  # pragma: no cover - CLI feedback
        print("\n" + "=" * 80)
        print("✗ GROUP CONNECTIVITY FAILED")
        print("=" * 80)
        print(f"Error: {exc}")
        print("=" * 80)
        return 1


if __name__ == '__main__':
    sys.exit(main())
